### ISSUE TITLE
Editing a post is automatically indenting paragraphs after the first one.

### ISSUE THREAD

**Issue by mu-arch** [LemmyNet/lemmyBB#56]
Editing a post automatically inserts indentation on paragraphs after the first one.

This causes an automatic blockquote once saved, which the user then has to go back and edit out. Tested on Firefox.

**Comment by Nutomic** [comment]
Can you link an example post where this happens, and steps to reproduce? Gonna have to add an issue template for this.

Anyway this might be because im doing some string replacing on generated markdown, otherwise there are `<p>` tags which mess up the layout.

https://github.com/LemmyNet/lemmyBB/blob/main/src/template_helpers.rs#L61

**Comment by mu-arch** [comment]
Well I went to make a new post to demo the issue and I'm getting a 500 now :smile: 

I'll try again tomorrow.

**Comment by Nutomic** [comment]
Fixed: af1c705a833f32c84bf9fac4925c83c7c6efeb68
